default:
  biodbdir: '{userdatadir}/biodb'
  uniprotdbfile: '{biodbdir}/uniprotdb.human.go.sqlite'
  compartmentsdbfile: '{biodbdir}/compartmentsdb.human.surface.sqlite'
  gtexdbfile: '{biodbdir}/gtexdb.summary.sqlite'
  evodevodbfile: '{biodbdir}/evodevodb.summary.sqlite'
  godbfile: '{biodbdir}/godb.assoc.sqlite'
  cirfessdbfile: '{biodbdir}/cirfessdb.human.spc.sqlite'
  jiangproteomedbfile: '{biodbdir}/jiangproteomedb.summary.sqlite'
  theratardbfile: '{biodbdir}/theratardb.gene_disease.sqlite'
  opentargetdb_populate: true
  cachesubdir: 'immunotar'

#these settings are meant for developers only (not for library/enduser)
devel:
  # immunotardeveldir is not a variable used/needed in the immunotar package. It is used by developers to set up their specific folders.
  immunotardeveldir: '..'
  #git.remoteurl: 'https://github.com/shraimrawan/IMMUNOTAR.git'
  #Please use the following remoteurl; you should already have permission to modify that github repository.
  #If you want to keep a separate GitHub repository in your own account, you can fork/copy it.
  git.remoteurl: 'https://github.com/sacanlab/immunotar.git'
  git.autopull: 1 #whether to pull when a push attempt tells us there are commits in the remoteurl.
  git.username: 'Sacanlab Devel' #overwrite this with your own Fullname in your subconfig section.
  git.email: '<>'  #you can leave this as is. I use this blank b/c I don't want to expose email addresses in the repository commit history.
  git.tokenfile: '{userhomedir}/github.token.immunotar.txt'
  datadir:    '{immunotardeveldir}/data'
  #datasetdir variable is not part of immunotar libray, but is used by developers for certain case studies.
  datasetdir: '{immunotardeveldir}/datasets'
  #The following file and url parameters will already default to those values. Leaving here as comments as examples in case you need to modify them.
  #depmapdbfile: '{biodbdir}/depmapdb.sqlite'
  #depmapdburl: 'https://sacan.biomed.drexel.edu/lic/downloadfile?file=depmapdb.sqlite'
  biodbdir:   '{immunotardeveldir}/../biodb'

rawan:
  #multiple levels of importsubconfig not working?? needs to be tested.
  config.importsubconfig: devel
  biodbdir:   '{immunotardeveldir}/../biodb'
  #packager.topdir: '..' #packager.topdir defaults to userhomedir/r.packager. Set here if you want it different.
  parallel_maxworkers: 5
  git.username: 'Rawan Shraim'



rawanlaptop:
  immunotardeveldir: '/Users/shraimr/Library/CloudStorage/Box-Box/RMS PhD Project/RMS_DIA/Code'
  #config.importsubconfig: rawan
  config.importsubconfig: devel


c02dk0sqml7j:
  #config.importsubconfig: rawan
  immunotardeveldir: '/Users/shraimr/Library/CloudStorage/Box-Box/Rawan/RMS PhD Project/RMS_DIA/Code'
  config.importsubconfig: devel
  

# You can change the defaults above, or set your computer-specific parameters by using a config group with your computername.
# You can also use a computer-specific file, e.g., config.yourcomputername.yml for settings that you want to use on a specific computer.
# Use "config.importfile: ..." or "config.importsubconfig: ..." to import the settings in another file or another subconfig.

