---
title: "Prioritize genes for a cancer type without providing additional experimental data"
DISABLED_output:
  html_document:
    df_print: paged
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Prioritize genes for a cancer type without providing additional experimental data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r}
# Create a project configuration:
proj = list(
	dataset='__ALLHUMANSURFACEGENES__'  # The starting point is all human surface genes
	,enrich=list(
		# Specify the databases that the dataset should be enriched with:
		enrichtypes='gtex,evodevo_pediatric,healthyprot,depmap,compartments_sp,cirfess_spc'
		# Some enrichment databases require additional inputs; e.g., Depmap database requires a disease name:
		,depmapids='Rhabdomyosarcoma')
);

# Perform dataset enrichment and prioritization analysis:
proj = immunotar::project_run(proj)

# Print the top ranking genes:
head(proj$datawithscore[,'score',drop=F])
```
