---
title: "R Notebook"
output: html_document
---



```{r}
##Testing all functions 
rm(list=ls())
source('depmapdb.r')
source('enrich_depmap.r')
source('enrich.r')
source('vec_rescale.r')
source('data_rescale.r')
source('data_weightapply.r')
source('data_score.r')
source('./vec_handlenan.r')
source('./data_summarize.r')
source('data_normalize.r')
source('data_combineduplicaterows.r')
source('biodb.r')
source('./data_handlena.r')
source('./getcoloption.r')
source('biodb.r')
source('./getquant.r')

biodb_file('gtexdb')

data=data.frame(exp1=c(1,2,3,4,5,6,7,11), exp2=c(4,5,9,NA,16,12,1,NA), exp3=c(3,7,10,9,100,12,71,20))
rownames(data)=c("MEGF10", "PLK1", "EEF2", "ZNF497", "ACOX2", 'FakeGene','FakeGene2', "TSPAN6")



#as.vector(data)

#HandleNAN will be used once for expression and then again prior to ranking 

b=data_normalize(data, 1:3, log_data = 'yes')
c=data_summarize(b, 1:3)
d=data_summarize(b, 1:3, highthreshold = "80%", lowthreshold = "20%" )
e=data_summarize(b, 1:3, highthreshold = 80, lowthreshold = 20 )
r=data_summarize(b, 1:3, highthreshold = NA, lowthreshold = NA )


##Enrichment 
d=enrich_compartments_sp(c)
e=enrich_depmap(d, "Rhabdomyosarcoma")
f=enrich_gtex(e)
g=enrich_jiangprot(f)
h=enrich_evodevo_pediatric(g)
d=enrich_cirfess_spc(data)


#Sample input for each colname 
input=data.frame(colname=c('numhighexpressed', "depmap_probability", 'compartments_sp_confidence'), rescale=c('percentile', 'rangemap0100', 'percentile'), weight=c(-1,1, 1), handlena=c("min", "max", 'min'))

config=read.delim("~/Library/CloudStorage/Box-Box/Rawan/RMS PhD Project/RMS_DIA/Code/src.r/configdf.csv", sep = ",", row.names = 1, header=T)


#Testing handle_nan

r=data_handlena(g, configdf = config)
r=data_handlena(g, default = 0, configdf = config)


#Testing_rescale
x=data_rescale(r, configdf = config)
q=data_rescale(r, rescale = 'rangemap0100', configdf = config)


#Testing score 
final_df=data_score(t, 4:12, 1)
final_df2=data_score(x, 4:12, input)


```


```{r}

source('enrich_depmap.r')
enrich_depmap(data,c('ALL','B-cell'))
```



```{r}
source('summarize_proteomics.r')

df=data.frame(a=c(1,2,3), b=c(3,6,7), c=c(8,11,2))

df_summary=summarizedata(df, c(1:3), "TPM", summarytypes = c("mean_expression"))

sum(c(83333.33, 250000.0, 666666.7))/3
```
