---
title: "stat_rank_demo"
output: html_document
date: "2023-01-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
rm(list=ls())
source('stat_rankeval.r')


#Testing examples from page 250 of the lecture notes: https://www.cl.cam.ac.uk/teaching/1516/InfoRtrv/lecture6-evaluation-2x2.pdf
#showing the calculated result vs. the answer on the slide:
c(stat_rankeval(1:20, c(1,3,6,10,20),order='ascend'), 0.564)

c(stat_rankeval(1:20, c(1,3,6,10,20), method='wmap', order='ascend', positiveweights=c(10,1,1,1,1)), 0.564)

c(stat_rankeval(1:15, c(1,3,15), order='ascend'),  0.623)

d=data.frame(score=c(1,2,3,3,3,4))
rownames(d)=c("a","b", "c", "d", "e", "f")
knownpositives="c"

stat_rankeval(d, knownpositives, method='map')

stat_rankeval(1:10, c(1,3,6,9,10),method = 'map', order='ascend')

stat_rankeval(1:10, c(2,5,6,7,8), order='ascend')

stat_rankeval(data.frame(score=c(5,10,20,30,40)), positives=c(1,5),positiveweights=c(1,1), method='map');
stat_rankeval(data.frame(score=c(5,10,20,30,40)), positives=c(1,5),positiveweights=c(200,100), method='wmap');

```
